name: Testing
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install third-party libraries (libcurl, libsodium)
        run: sudo apt-get install libcurl4-openssl-dev libsodium-dev
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.1'
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install Renv R package manager
        run: |
          remotes::install_github("rstudio/renv")
          renv::consent(provided = TRUE)
#          install.packages(c("renv"))
        shell: Rscript {0}
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      # - name: Install R libraries
      #   run: |
      #     renv::install(c("dplyr", "stringi",  "readr", "textmineR", "plumber"))
      #   shell: Rscript {0}
      #- name: Run climate data
      #  run: | 
      #    Rscript run-climate-data.R
      #    Rscript run-topic-analyser.R
      #    ./run-test.sh
#, "ggplot2", "stringi",  "readr", "textmineR", "ggwordcloud", "gridExtra", "remotes"
#          remotes::install_deps(dependencies = TRUE)
